CREATE DATABASE IF NOT EXISTS matcha DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `matcha`;

CREATE TABLE IF NOT EXISTS `users`(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uname VARCHAR(255) NOT NULL,
    lname VARCHAR(255) NOT NULL,
    fname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    age VARCHAR(255) NULL,
    sexual_orientation VARCHAR(255) NULL,
    gender VARCHAR(255) NULL,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    confirmation INT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS profil_user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uid INT NOT NULL,
    tag VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS `like` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uid_1 INT NOT NULL,
    uid_2 INT NOT NULL,
    like_1 INT(1) NULL DEFAULT 0,
    like_2 INT(1) NULL DEFAULT 0
);
